# 0. (Optional) Set docker-compose.dev.yaml as default:
#     echo 'COMPOSE_FILE=docker-compose.dev.yaml' >> .env
#
# 1. Prepare your workspace by:
#     docker compose run --rm web npm install
#
# 2. Start you work by:
#     docker compose up -d
#
# 3. Check logs by:
#     docker compose logs -f
#
services:
  api:
    image: cosmtrek/air:v1.52.2
    working_dir: /work
    command: -c ./scripts/.air.toml
    volumes:
      - .:/work/
      - ./data/gocache/:/root/.cache/go-build/ #Go build cache
      - ./data/gomod/:/go/pkg/mod/ #Go mod cache

  web:
    image: node:18.12.1-alpine3.16
    working_dir: /work
    depends_on: ["api"]
    ports: ["3001:3001"]
    environment: ["DEV_PROXY_SERVER=http://api:8081/"]
    command: npm run dev
    volumes:
      - ./web:/work
      - ./data/node_modules/:/work/node_modules/ # Cache for Node Modules
