name: build-release

on:
  release:
    types: [created,edited]
  push:
    branches: [main]

jobs:
  build-and-push-release-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Extract assets from Docker Image
        id: extract
        uses: shrink/actions-docker-extract@v2
        with:
          image: ghcr.io/usememos/memos:v0.13.1
          path: "/usr/local/memos/memos"
          
      - name: Upload Release Assets
        uses: AButler/upload-release-assets@v2.0
        with:
          files: ${{ steps.extract.outputs.destination }}
          release-tag: "v4"
