name: build-release

on:
  release:
    types: [created,edited]

jobs:
  build-and-push-release-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Debug Tag Name
        run: echo ${{ github.release.tag_name }}
      - name: Debug Name
        run: echo ${{ github.release.name }}}}
      - name: Debug release
        run: echo ${{ github.release }}
      - name: Extract assets from Docker Image
        id: extract
        uses: shrink/actions-docker-extract@v2
        with:
          image: usememos/memos:${{ github.release.tag_name }}
          path: "/usr/local/memos/memos"
          
      - name: Upload Release Assets
        uses: AButler/upload-release-assets@v2.0
        with:
          files: ${{ steps.extract.outputs.destination }}
          release-tag: "v4"
