name: Update Release Assets

# 触发条件
on:
  release:
    types: [created, edited]
  push:
    branches: [main]

jobs:
  extract_upload_files:
    runs-on: ubuntu-latest
    steps:
    
    - name: "Debug"
      run: echo ${{ github.ref }}

    - name: Get Version for release
      env:
        VERSION: ${{ github.event.release.tag_name }}
    - name: Get Version for branch
      if: startsWith(github.ref, 'refs/branch')
      env:
        VERSION: "latest"

    - name: "Debug"
      run: echo $VERSION
    - name: Extract files from docker image
      run: |
        docker pull ghcr.io/usememos/memos:${{ env.VERSION }}
        docker create --name tmp ghcr.io/usememos/memos:${{ env.VERSION }}
        docker cp tmp:/usr/local/memos/memos memos
        docker cp tmp:/usr/local/memos/memos memos2
        tar cvzf release.tbz2 memos memos2

    - name: Upload extracted files to release assets
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name:  ${{ github.event.release.tag_name || "0.13.0" }}
        files: release..tbz2
